### ISSUE TITLE
Servos require sudo usage?

### ISSUE THREAD

**Issue by nezra** [mcdeoliveira/rcpy#13]
The C code from strawson design no longer require Sudo access to operate. However, using this library still requires sudo access, else it errors out. 

I can provide examples if needed, however the code provided for examples will reflect this.

**Comment by StrawsonDesign** [comment]
librobotcontrol still requires root access for servos and any other PRU access. This is due to the fact that the remoteproc driver does not present the PRU's shared memory to the user so it must be accessed with /dev/mem which requires root access. It might be possible to expose that memory as its own device with normal-user access by setting up a generic memory map in the device tree, but I've not been able to do this. See this open request: https://github.com/StrawsonDesign/librobotcontrol/issues/132
